apiVersion: v1
kind: Service
metadata:
  name: redis-crud-service
  namespace: dev
  labels:
    type: application
    tier: backend
spec:
  type: LoadBalancer
  selector:
    type: api-server-go
    tier: backend
  ports:
    - nodePort: 31900
      port: 9000
      targetPort: 9000
